version: '3.9'

services:
  go-app:
    container_name: task_list
    image: task_list:latest
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "listen_addresses='*'"]

volumes:  
  pgdata: {}